spring.application.name=CinemaArchive
spring.datasource.url=jdbc:sqlite:MoviesDataBase.db
spring.datasource.driverClassName=org.sqlite.JDBC
spring.jpa.properties.hibernate.dialect=com.example.CinemaArchive.SQLiteDialect
spring.jpa.show-sql=true
spring.datasource.hikari.read-only=false
spring.datasource.hikari.connection-test-query=SELECT 1
spring.sql.init.platform=sqlite


